// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlnBDuqrG9DiwdarS2H2iZXhr2IzAq1bM',
    appId: '1:119948554671:web:fc13c7a8836ab824b23f5a',
    messagingSenderId: '119948554671',
    projectId: 'maruthi-eats',
    authDomain: 'maruthi-eats.firebaseapp.com',
    storageBucket: 'maruthi-eats.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlnBDuqrG9DiwdarS2H2iZXhr2IzAq1bM',
    appId: '1:119948554671:android:df08f278e1dc83d5b23f5a',
    messagingSenderId: '119948554671',
    projectId: 'maruthi-eats',
    storageBucket: 'maruthi-eats.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlnBDuqrG9DiwdarS2H2iZXhr2IzAq1bM',
    appId: '1:119948554671:ios:4021022676f5077cb23f5a',
    messagingSenderId: '119948554671',
    projectId: 'maruthi-eats',
    storageBucket: 'maruthi-eats.firebasestorage.app',
    iosBundleId: 'com.example.maruthi_eats',
  );
}
